name: Build and test

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    # run on macOS so it can do ui stuff
    runs-on: macos-latest

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.4.0
        uses: actions/setup-node@v1
        with:
          node-version: "12.4.0"
      - name: Build
        run: |
          npm install
          npm run compile
          npm run lint
      - name: Tests
        run: npm test
      - name: Clean and prep for packaging
        run: |
          npm run clean
          npm install
      - name: Compile for packaging
        run: npm run compile
        env:
          NODE_ENV: production
      - name: Package extensions
        run: |
          npm run vscode:package
          # upload-artifact doesn't support globs, so put them in a single folder
          mkdir dist-extensions
          find . -name '*.vsix' -type f -exec mv {} dist-extensions \;
      - name: Upload extensions
        uses: actions/upload-artifact@v1
        with:
          name: extensions
          path: dist-extensions
