name: PR build and test

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  pr-build:
    # run on macOS so it can do ui stuff
    runs-on: macOS-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.11.0
        uses: actions/setup-node@v1
        with:
          node-version: 10.11.0
      - name: Build and test
        run: |
          npm install
          npm run compile
          npm run lint
          npm test
